For any transform, start with $M$ as identity matrix and apply desired linear transform to $M$ - eg. linear combination of input matrix's columns/rows, inserting/deleting columns/rows.
Final result matrix is $A = M B$ for column transform, or $A = B M$ for row transform.

Common case of scaling a single row/column is done with a _diagonal matrix_, eg. `np.diag([2,1,1,1])` - all 1s in diagonal, except for multiplier at the row/column index to be scaled (here 1st column is to be doubled).

#### Solution Derivation (column transform)

Explanation for the first task, remaining tasks are similar:

- First task is to double first column of input matrix $B$. We'll calculate transform matrix $M$ such that $A = M B$ .
- Column vectors of input $B$ are transformed by $M$ to get result matrix column vectors:
  $$[\mathbf{a_1}, \mathbf{a_2}, \mathbf{a_3}, \mathbf{a_4}] = [M \mathbf{b_1}, M \mathbf{b_2}, M \mathbf{b_3}, M \mathbf{b_4}]$$
- Each column vector of $M$ can be written in terms of _unit basis vectors_ $\mathbf{e_i}$. In this task, transforming first column doubles it (2x), rest remain same (1x). So:
  $$M = [M \mathbf{e_1}, M \mathbf{e_2}, M \mathbf{e_3}, M \mathbf {e_4}] = [2 \mathbf{e_1}, \mathbf{e_2}, \mathbf{e_3}, \mathbf{e_4}]$$
- Unit basis vector $\mathbf{e_i}$ has $1$ at index $i$, $0$ everywhere else. So expanding above into full transform matrix:
  $$
  M = \begin{bmatrix}
  2 & 0 & 0 & 0 \\
  0 & 1 & 0 & 0 \\
  0 & 0 & 1 & 0 \\
  0 & 0 & 0 & 1 \\
  \end{bmatrix}
  $$
  NOTE: This is a **Diagonal matrix** (since values are only on main diagonal, rest are 0). So it's written simply as $np.diag([2,1,1,1])$ .
- Final result matrix is $A = M B$ .

#### Solution Derivation (row transform)

- We'll calculate transform row matrix $M$.
- We can transpose input $B$, calculate [column transform](#solution-derivation-column-transform) matrix $M^T$, then transpose back to get final result: $A = (M^T B^T)^T$ .
- But $(P Q)^T = Q^T P^T$, so we get $A = B M$ .

#### Naming Convention

In the below code (unlike usual Python naming convention), matrix variable names start with capital letters to keep it consistent with _README.md_ .


In [1]:
import numpy as np
B = np.reshape(np.random.permutation(np.arange(4*4)), (4,4))    # test input matrix

#### Main Code


In [2]:
Bdirect = B.astype('float')
Btransform = B.astype('float')

t1 = 'double column 1'
M1 = np.diag(np.array([2,1,1,1]))
Btransform = Btransform @ M1
Bdirect[:, 0] *= 2
assert (Btransform == Bdirect).all(), f'{t1} - both answers different!'

t2 = 'halve row 3'
M2 = np.diag(np.array([1,1,0.5,1]))
Btransform = M2 @ Btransform
Bdirect[2, :] /= 2
assert (Btransform == Bdirect).all(), f'{t2} - both answers different!'

t3 = 'add row 1 to row 3 '
M3 = np.identity(4)
M3[2,0] = 1
Btransform = M3 @ Btransform
Bdirect[2, :] += Bdirect[0, :]
assert (Btransform == Bdirect).all(), f'{t3} - both answers different!'

t4 = 'interchange columns 1 and 4'
M4 = np.identity(4)
M4[:, [0,3]] = M4[:, [3,0]]       # cool numpy slicing (select non-contigous columns explicitly!)
Btransform = Btransform @ M4
Bdirect[:, [0,3]] = Bdirect[:, [3,0]]
assert (Btransform == Bdirect).all(), f'{t4} - both answers different!'

t5 = 'subtract row 2 from rest 3 rows'
M5 = np.identity(4)
M5[[0,2,3], 1] = -1
Btransform = M5 @ Btransform
Bdirect[[0,2,3], :] -= Bdirect[1]
assert (Btransform == Bdirect).all(), f'{t5} - both answers different!'

t6 = 'subtract row 2 from rest 3 rows'
M6 = np.identity(4)
M6[:, 3] = M6[:, 2]
Btransform = Btransform @ M6
Bdirect[:, 3] = Bdirect[:, 2]
assert (Btransform == Bdirect).all(), f'{t6} - both answers different!'

t7 = 'delete column 1'
M7 = np.delete(np.identity(4), 0, axis=1)   # axis 0 is 'index', 1 is 'column'
Btransform = Btransform @ M7
Bdirect = np.delete(Bdirect, 0, axis=1)
assert (Btransform == Bdirect).all(), f'{t7} - both answers different!'

#### Answer to (a)


In [3]:
print('PRODUCT OF 8 MATRICES (in order):')
for t, transform_matrix in [(t5,M5), (t3,M3), (t2,M2), ('ORIGINAL',B), (t1,M1), (t4,M4), (t6,M6), (t7,M7)]:
    print('\n', t)
    display(transform_matrix)
assert (M5 @ M3 @ M2 @ B @ M1 @ M4 @ M6 @ M7 == Btransform).all()

PRODUCT OF 8 MATRICES (in order):

 subtract row 2 from rest 3 rows


array([[ 1., -1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0., -1.,  1.,  0.],
       [ 0., -1.,  0.,  1.]])


 add row 1 to row 3 


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.]])


 halve row 3


array([[1. , 0. , 0. , 0. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 0.5, 0. ],
       [0. , 0. , 0. , 1. ]])


 ORIGINAL


array([[14,  6,  8,  1],
       [ 4,  2,  7,  0],
       [10,  3,  5,  9],
       [13, 15, 11, 12]])


 double column 1


array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])


 interchange columns 1 and 4


array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])


 subtract row 2 from rest 3 rows


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 0., 0.]])


 delete column 1


array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Answer to (b)

Since matrix multiplication is associative $(A B) C = A (B C)$, but NOT commutative $A B \neq B A$,
we can multiply any 2 matrices first and substitute result as long as overall multiplication order is maintained.


In [5]:
print("PRODUCT OF 3 MATRICES (middle not shown as it's same as input matrix):")
Left = M5 @ M3 @ M2
Right = M1 @ M4 @ M6 @ M7
print('LEFT:')
display(Left)
print('RIGHT:')
display(Right)
assert (Left @ B @ Right == Btransform).all()

PRODUCT OF 3 MATRICES (middle not shown as it's same as input matrix):
LEFT:


array([[ 1. , -1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 1. , -1. ,  0.5,  0. ],
       [ 0. , -1. ,  0. ,  1. ]])

RIGHT:


array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 1.],
       [0., 0., 0.]])

#### Output Matrix for Test Input


In [6]:
Btransform

array([[ 4. ,  1. ,  1. ],
       [ 2. ,  7. ,  7. ],
       [ 5.5,  3.5,  3.5],
       [13. ,  4. ,  4. ]])